name: Nx Action
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Nrwl Nx
  # You may pin to the exact commit or the version.
  # uses: MansaGroup/nrwl-nx-action@aa23d6b1e0aa2aefe44026c2afe31b6a0b48c657
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
    # Comma-separated list of targets to execute
          targets:
    # Comma-separated list of projects to use
          projects: # optional
    # Run the targets on all projects
          all: # optional, default is false
    # Use the Nx' affected subcommand to only process affected projects
          affected: # optional, default is true
    # Run the tasks in parallel (can be expensive)
          parallel: # optional, default is false
    # Number of tasks to execute in parallel (can be expensive)
          maxParallel: # optional, default is 3
    # Optional arguments to append to the Nx command
          args: # optional, default is
    # Enable support for Nx Cloud
          nxCloud: # optional, default is false
    # Path to the Nx workspace, needed if not the repository root
          workingDirectory: # optional
