---
-
  name: "Nrwl Nx"
  uses: MansaGroup/nrwl-nx-action@v2.1.0
  with:
    affected: "true"
    all: "true"
    args: ~
    maxParallel: ~
    nxCloud: ~
    parallel: "true"
    projects: ~
    targets: "lint,test,build"
    workingDirectory: ~
